[build]
publish = "preview-dist"
command = "npm run preview"

[build.environment]
CI = "true"
NODE_VERSION = "16"

[context.deploy-preview]
command = "npm run preview && npm run build"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
