[build]
publish = "public"
command = "node_modules/.bin/gulp preview:build"

[build.environment]
CI = "true"
NODE_VERSION = "10"

[context.deploy-preview]
command = "node_modules/.bin/gulp preview:build && node_modules/.bin/gulp --series build bundle:pack"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
