name: Build and Upload UI Bundle

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout @v4
      - name: Setup mise and install tools
        uses: jdx/mise-action @v1
        with:
          install: true
      - name: Install dependencies
        run: npm ci
      - name: Build UI bundle
        run: npm run build
      - name: Upload release asset
        uses: softprops/action-gh-release @v1
        with:
          files: build/ui-bundle.zip